INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1800', 'Automatically generate SPL with Number Plan changes (Scheduler)','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2109', 'Release Contract Manager as part of normal release - AOR','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2076', 'Create ICT 7.1 SP11 Escrow check-in','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2035', 'Improve ICT VBR calculation performance by refactoring selects from VBR_DLYS_NETT_VIEW','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2090', 'Improve ICT VBR calculation performance by refactoring Billing Period Select','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2094', 'Remove configuration restrictions for Summary Relocate','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2092', 'Consolidated Installer','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2097', 'Implement configurable cache mechanism for Summary rerate history','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2095', 'Enable Summary relocate to run in background together with other processes','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1816', 'Spring Framework 4','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1983', 'IFM: Support for SFTP for file distribution (Invoice, ERP & Reports)','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-647' , 'Credit Management BO Reports - Agreement Balance History','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2082', 'Container based Automatic Deployment of PTL','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1917', 'Automate the Installation of Tomcat','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2083', 'Container based Automatic Deployment of IFM','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2084', 'Automate Security Testing Build Steps','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2085', 'Automate the Full Batch Regression','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2086', 'Automate the Platform regression testing','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1831', 'GBET Import: Add Price Model to Agreement API','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1826', 'SQL*Server Standard Edition recommendation','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2052', 'Route - Performance Tuning Existing ARP Delta ETL Load','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2059', 'Resurrect RC Automation and Regression','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2049', 'IFM - Export Reference Data script - output file naming','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2106', 'WBMS-WEB-UI - Login & Security','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1809', 'RJIL - Security Vulnerability - Session fixation and hijacking IFM','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2101', 'Reference Data APIs required for IBS Rate Lookup API (Dispute Management)','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1570', 'Last Login and Policy Display - Portal','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2103', 'Last Login and Policy Display - WBMS-WEB-UI','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2034', 'Login Security Additions','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1811', 'CheckMarx - Fix IFM Reflected XSS All Clients Exploit','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1765', 'Ref Data Integration: Retrieve, Create & Update ICT POIs and ICT Paths directly from CSG Route','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1819', 'Vimpelcom - Generic Select Bulk Loader Enhancement','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2067', 'Change IFM Styling to be in line with INT-WEB-UI Styling','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2065', 'Change PTL, CDM & PRM Styling to be in line with INT-WEB-UI Styling','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2087', 'Investigate Automation of the Process for Release Candidate Creation and Versioning for the next Release','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2088', 'Build Pipeline Live View Application','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-2089', 'Build Pipeline Aggregation Components','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1643', 'Dashboard Run As At Date for Demos','',0);
INSERT INTO Feature(ID, Name, URL, Votes)	VALUES ('WBMS-1919', 'Migration to Symantec Cloud Signing Service','',0);